Title: A basic project
ID: CCBR-1000001
Collaborator:
  - Collaborator 1
  - Collaborator 2
Participants:
  - Sean
  - Maggie
  - Peter
  - Randy
  - outside person: This person did nothing but insisted that he be on any future papers
